version: '3.8'

networks:
  market-net:
    driver: bridge

volumes:
  redis_data:
    name: contracts_redis_data

  postgres_data: {} 


services: 
  marketflow:
    container_name: marketflow
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env   
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - market-net

  postgresql:
    image: postgres:16.3
    hostname: postgresql
    ports:
      - 5432:5432
    networks:
      - market-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: marketflow
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d marketflow"]
      interval: 10s
      timeout: 5s
      retries: 5


  migrate:
    image: migrate/migrate
    networks:
      - market-net
    volumes:
      - ./migrations:/migrations
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://user:admin@postgresql:5432/marketflow?sslmode=disable",
        "up"
      ]
    depends_on:
      postgresql:
        condition: service_healthy

  redis:
    image: redis:7.2-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./local/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-strongpassword}
    restart: unless-stopped
    networks:
      - market-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  exchange1:
    image: exchange1:latest
    container_name: exchange1
    ports:
      - "40101:40101"
    networks:
      - market-net

  exchange2:
    image: exchange2:latest
    container_name: exchange2
    ports:
      - "40102:40102"
    networks:
      - market-net

  exchange3:
    image: exchange3:latest
    container_name: exchange3
    ports:
      - "40103:40103"
    networks:
      - market-net